### ISSUE TITLE
On Raster Import - Mac OS

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/RIPTPlugin#12]
Hey @KellyMWhitehead - this is the error messaging I got when attempting the import of a detrended raster.

![on-import-raster](https://user-images.githubusercontent.com/34071692/122591742-3f9d5480-d018-11eb-8de2-19a2138f952b.png)

**Comment by MattReimer** [comment]
This is almost certainly a path issue. Make sure you're using python's os.path tools to parse paths in an OS-agnostic way.

Things like `path.sep` are really useful here.

**Comment by KellyMWhitehead** [comment]
It was related to a path issue, the project path wasn't set in the ript_project object when creating a new project. I didn't catch this since most of my testing was based on opening existing projects.

Fixed in 93839fbbdd757ee7906962fe2e64de247026e797
