### ISSUE TITLE
RIPT Toolbar with create project and open project buttons

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RIPTPlugin#3]
Here's the first feature request for RIPT. Everything below is 100% copying how GCD works! This is a proven strategy that perfectly fits how we see RIPT working.

# Requirements

1. The plugin needs to have a toolbar.
2. The toolbar has two buttons:
    1. Create new project
    2. Open existing project.

## Create New Project

* Clicking the create new project button opens a form that allows the user to provide about the new project:
   * plain text name of the project
   * file path where the project will get saved.
       * like the GCD, the user picks the **folder** where the project will get created (not the file path). The software then automatically generates the full path by creating a folder inside the folder where the user clicked with the same name as the project (with dangerous characters removed).
       * An XML file is created called `project.ript` (this is custom hierarchy of RIPT information)
       * Another XML file is created called `project.rs.xml` (this is the riverscapes compatible project file) 
* Clicking OK creates the folders and files described above.
* Once the files are created then a dockable window is opened in QGIS that contains the project tree. Note that this is **not** the riverscapes project tree driven by business logc!!!!! This is the custom tree for RIPT!
    * the top item in the tree is the name of the new RIPT project
    * Under the project tree is a static node called "Detrended Topography"
    * (obviously a lot more to come here. This is just the start!)

## Open Existing Project

* Clicking this button lets the user browse for RIPT project files (`*.ript`). 
* One the user selects their existing ript project file the dockable window described above opens, populated with the contents of the project that the user just browsed.

# Questions

* What vector data format do we intend to use? If it's GeoPackages then what dimensionality? One per layer? One for inputs, one for intermediates, one for outputs? Or one per data type (e.g. flow lines in the example below)? Need to think about connection strings, reporting, synthesizing data.
* See next point about two XML files? Do we even need a RIPT XML file if all the layers are in one or more GeoPackages? Can the GeoPackages become the project definition?
* Do we still need two XML files now that we have abandoned realizations in the riverscapes project XML? Here's the XML I anticipate:

```xml
<RIPT>
    <NAME>My cool Project</NAME>
    ...other metadata here
   <DetrendedRasters>
        <Raster>
            <Name>My cool detrended surface</Name>
            <Path>DetrendedRasters/DR0001/raster.tif</Path>
        </Raster>
        <Raster>
            <Name>Yet another detrended raster</Name>
            <Path>DetrendedRasters/DR0002/raster.tif</Path>
        </Raster>
    </DetrendedRasters>
    <FlowLines>
        <Vector>
            <Name>My hand drawn flow lines</Name>
            <Path>FlowLines/FL0001/flowlines.shp</Path>
        </Vector>
        <Vector>
            <Name>NHD flow lines imported from riverscapes context</Name>
            <Path>FlowLines/FL0002/flowlines.shp</Path>
        </Vector>
    </FlowLines>
    .... obviously lots more stuff here
</RIPT>
```

FYI @MattReimer @joewheaton @nick4rivers

**Comment by nick4rivers** [comment]
@philipbaileynar - thanks for getting this moving. I think this begins to lay out what a component of RIPT will be. But, I do think that our discussion needs to be at bit higher level and describe just what RIPT is/does? Following this we can begin to move toward developing the tree, inputs, outputs, UI, etc...We will probably need some insight from @joewheaton on this.

So, here are a series of statements that at a high - level might help define what RIPT "is", what it "will" do, and what it "can" do. Ript:
 - **_is_** an LTPBR planning and design tool implemented as a **_QGIS plugin_**.
 - **_is_** a first iteration of what will become a similar tool implemented as a **_progressive web app_**?
 - **_will_** support export of **_riverscapes compatible_** spatial spatial data.
 - **_will_** have a **_slider toolbar_** that allows interactive symbolization of elevation surfaces, e.g., detrended DEM data.
 - **_can_** **_consume/process/symbolize an array of spatial data / model outputs_** to be incorporated into and inform LTPBR planning and design.
 - **_will_** support the documentation of LTPBR **_planning_** components, e.g., active channels, floodplains, terraces, human infrastructure risks, etc.....
 - **_will_** support documentation of LTPBR **_design_** components, e.g., reaches, complexes, structures.
 - **_can_**support the documentation/capture of riverscape **_assessment_** features, e.g., wood jams, dams, confluences, etc...
 - **_can_** support the **_export of standard maps, graphics, text, figures_** that summarize LTPBR information.
 - **_is_** intended to be available to and **_used by individuals outside_** of our (e.g., anabranch, USU, etc...) group.

@joewheaton , @philipbaileynar @MattReimer - What else do we know? Can we remove, refine, or extend the items on this list - e.g., what about a mobile component implemented in QField? If this is a good starting point we can move from here into better organization and the specifics of these items?

**Comment by philipbaileynar** [comment]
Thanks for the input @nick4rivers. This is good material. Can you please take the content you posted on this issue and move it into the Google Docs document. That's a more appropriate place for strategic discussion, explanation, planning.

I welcome the level of thinking that you suggest. I just think that should go in the Google doc. And keep GH issues for specific software features/enhancements.

**Comment by nick4rivers** [comment]
Ha @philipbaileynar - yes, was thinking the same thing as I wrote that up!!

**Comment by KellyMWhitehead** [comment]
Tree view and basic project class created for RIPT, and ability to save and open a basic project.ript xml file.

![image](https://user-images.githubusercontent.com/10746997/120840048-925a1500-c51e-11eb-998f-a18aef565f8f.png)
