### ISSUE TITLE
Outputting a Vector file using Qgs and Processing

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RIPTPlugin#4]
This ticket just creates a link between @nick4rivers initial experiment with Qgs vector creation

@KellyMWhitehead when you get to the place where you need to implement some Processing operations this will be an excellent starting place. 

https://github.com/nick4rivers/Q-polyvation/blob/master/polyvation.py

**Comment by KellyMWhitehead** [comment]
I incorporated this workflow in the vectorize tool for RIPT.
