### ISSUE TITLE
Add Detrended Raster

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RIPTPlugin#5]
Next feature for RIPT is "Add Existing Detrended Raster to Project".

Again, this workflow will be [very similar to the way GCD works](http://gcd.riverscapes.xyz/Help/Inputs/dem-surveys.html) when adding DEMs!

1. User right clicks on "Detrended Rasters" branch of project tree
2. Chooses "Add Existing Detrended Raster to Project" from context menu
3. File browser dialog opens where the user picks an existing detrended raster on their file system.
4. "Detrended Raster Properties" form appears. This is very similar to the GCD DEM properties form. Some key concepts:
    * Detrended raster name textbox defaults to name of the file user just browsed to (omitting file extension)
    * original raster text box is read only. Shows the full path to the raster the user just clicked on.
    * project raster path is read only text box showing the **relative** path to where the raster will get copied too.
        * We need a short folder name (`Detrended`?) then a zero padding folder with a prefix (`DET0001`) and then the file . name. In GCD this file name is a "safe" version of the DEM name. i.e. punctuation removed.
        * The zero padding is essentially a 1 based index of detrended rasters in the RIPT project.
5. When the user clicks "OK":
    * the original raster is copied to the project raster path. (Use QGIS GDAL geoprocessing? Will be a big file.)
    * the new detrended raster will get added to the RIPT project XML.
    * RIPT project tree refreshes to show the new raster.
    * Add new raster to the map?

# Notes

* Don't bother (for now) with showing the user all the raster properties (rows, cols etc) like the GCD does.
* In the future we can expand the raster properties screen with more useful stuff. Such as a metadata user control etc. Don't bother with any of this for now.

**Comment by KellyMWhitehead** [comment]
Detrended rasters are now getting added to the project. Does not add to map yet.
