### ISSUE TITLE
Elevation Explorer Feature

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RIPTPlugin#6]
1. Right click on detrended raster in project tree and choose "Explore Elevations..."
2. Dockable window opens with the following controls:
    1. Readonly text box of the detrended raster name that the user just clicked on (note name, not path)
    2. Slider control. Initial value is zero.
    3. readonly textbox showing the current value of the slider. (i.e. textbox value updates as slider is moved).
    3. button to export elevation polygon (see export section below)
1. Moving the slider resymbolizes the raster. Elevations below the value of the slider are solid pink (later we will let the user pick the color) and values above are the original HAND symbology. See symbology notes below.

## Symbology

Option 1: The detrended raster is added to map as grey scale. Moving the slider alters the layer color ramp so that values below the slider value are coloured pink (for now), values above the slider value are grey scale.

Option 2: The detrended raster is added to map with HAND symbology (brown to white colour ramp). Values below the slider are pink, values above slider are HAND symbology.

Option 3 (easiest): The detrended raster is added to a ToC Group Layeer **TWICE**. The bottom copy is coloured with HAND, while the top copy has the slider symbology applied: Raster values below the slider value are pink, while those above the slider value are transparent.

## Export

Clicking export runs @nick4rivers vectorization script using the current slider value as the threshold. A form pops open with the following controls:

* Name of the new surface - defaults to Surface From XXXXX at Detrended Elevation YYYYYYm (where XXXXX is the name of the detrended raster and YYYYYY is the slider value.)
* Readonly textbox showing the relative path where the polygon layer is going to get produced. e.g. `DetrendedRasters\DR0001\Surfaces\surfaces.gpkg` (assuming that all surfaces for a particular raster are put in a single geopackage.
* Maybe a type dropdown (valley bottom, active floodplain, inactive floodplain, zone of influence)

Clicking OK:

1. saves the polygon layer to disk
2.  adds the appropriate XML node in the RIPT project XML.
3. Adds the new polygon layer to the map (nested under the detrended raster)
4. Refreshes the RIPT project tree panel to show the new item.

**Comment by philipbaileynar** [comment]
FYI The inspiration for the form that pops up when you click "export surface" comes from several similar forms in GCD. Perhaps the closest one is the top half of the [associated surface properties](http://gcd.riverscapes.xyz/Help/Inputs/associated-surfaces.html#edit-properties) form. Ignore the properties section for now.

![gcd](http://gcd.riverscapes.xyz/assets/images/CommandRefs/00_ProjectExplorer/inputs/assoc/assoc_properties.png)

**Comment by nick4rivers** [comment]
@KellyMWhitehead  - sounds like this is up and running. I'll try to get the plugin running here tomorrow and give it a test drive. Thanks for busting this stuff out.
