### ISSUE TITLE
QGIS VSCode Integration

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/RIPTPlugin#9]
Yo @MattReimer or @KellyMWhitehead, either of you two have an answer for better integration between the QGIS python libraries and VScode linting? Would be nice if VScode didn't see everything specific to QGIS as a problem with my code?

![Screen Shot 2021-06-08 at 3 03 20 PM](https://user-images.githubusercontent.com/34071692/121263897-2d2e5880-c86b-11eb-8d0d-143d21604ba0.png)

**Comment by KellyMWhitehead** [comment]
Hey @nick4rivers , I was having the same issue and I think I stumbled on to a solution.

Take a look at the .bat file you use to kick off vscode in 'qgis mode'. Several of the paths were set to look for "...\apps\qgis", however when I navigated there, I found "...\apps\qgis-ltr" instead (ltr = Long Term Release?). When I updated the paths in the .bat file, vscode was able to import the qgis modules correctly.

**Comment by nick4rivers** [comment]
@KellyMWhitehead  - much appreciated. I could totally be wrong, but I think that .bat files are a windows thing. I may need to look in to my PATH references of where python looks for the QGIS models. I just can't totally figure out where that is.

@MattReimer  - if you have any insight let me know otherwise I'll close this out.

**Comment by MattReimer** [comment]
I've been working on this for a while. Almost have a solution. Watch this space.

**Comment by MattReimer** [comment]
OK. I looked for any way to do this that didn't involve setting `.bashrc` env vars but I wasn't able to find it

I've patched the `Workspaces/RIPTOSXDev copy.code-workspace` file to use an environment variable and updated the README.md with instructions. (I did this all for QRAVEPlugin too)

@nick4rivers the TL;DR is the following

0. pull the latest `dev` so you get the changes I just pushed
1. You need to add the following line at the bottom of your `~/.bashrc` or `~/.zshrc` file:

```bash
export QGIS_PATH=/Applications/QGIS.app
```

***NOTE: This path must not end in a slash and must match what's on your system. If you're using the LTR version of QGIS this path might be something like `/Applications/QGIS-LTR.app`***

After this is done you need to restart VSCode completely (not just relloading the window).

2. You need this user setting to be on (it's in the user settings preferences)

```
"terminal.integrated.allowWorkspaceConfiguration": true
```

3. Open up the `Workspaces/RIPTOSXDev copy.code-workspace` using VSCode. This file contains all the right environment variables necessary to find and work with QGIS python libraries.

-----------

If this doesn't work call me. It's probably something simple like a path in the wrong place.

**Comment by nick4rivers** [comment]
@MattReimer this awesome. Thanks a ton....I'll let you know if I get stuck.
